import './globals.css';
import Link from 'next/link';
import LoginBtn from './LoginBtn';
import LogOutBtn from './LogOutBtn';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/pages/api/auth/[...nextauth]';
import RegisterBtn from './RegisterBtn';
import Darkmode from './Darkmode';
import { cookies } from 'next/headers';

export const metadata = {
  title: 'next.js_게시판',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions);
  //console.log('로그인중인 유저', session?.user);

  let res = cookies().get('mode');
  return (
    <html lang="ko">
      <body
        className={res && res.value === 'dark' ? 'dark-mode' : ''}
        suppressHydrationWarning={true}>
        <div className="navbar">
          <Link href="/" className="logo">
            myBlog
          </Link>
          <Link href="/list">List</Link>

          {session ? (
            <>
              <Link href="/write">write</Link>
              <span className="welcome">{session.user.name}님 환영합니다</span>
              <LogOutBtn />
            </>
          ) : (
            <>
              <RegisterBtn />
              <LoginBtn />
            </>
          )}
          <Darkmode />
        </div>

        {children}
      </body>
    </html>
  );
}
